name: transmit
version: 1.0.0
author: Paul VanKeuren <paul.vankeuren@gmail.com>
description: A dart package that allows for quick event passing between distinct parts of your codebase.
dev_dependencies:
  browser: any